// <auto-generated />
// Generated Time: 07/26/2020 22:52:06
// Generated By: mah

namespace System.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfieldtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfieldtime));
        
        string IMigrationMetadata.Id
        {
            get { return "202007261822059_addfieldtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
