// <auto-generated />
// Generated Time: 07/23/2020 01:18:17
// Generated By: mah

namespace System.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class time_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(time_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202007222048177_time_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
