// Generated Time: 02/28/2020 19:40:46
// Generated By: mah

namespace System.Data.Entity.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class createlogtable : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.TB_APP_LOG",
                c => new
                    {
                        ID = c.Long(nullable: false, identity: true),
                        MESSAGE = c.String(maxLength: 150),
                        STACK = c.String(unicode: false),
                        DATE_OF = c.DateTime(nullable: false),
                        LOG_LEVEL = c.String(maxLength: 30),
                    })
                .PrimaryKey(t => t.ID);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.TB_APP_LOG");
        }
    }
}
