// Generated Time: 07/23/2020 01:18:17
// Generated By: mah

namespace System.Data.Entity.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class time_field : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.TB_CLASSES", "TIMEOF", c => c.String(maxLength: 10));
        }
        
        public override void Down()
        {
            DropColumn("dbo.TB_CLASSES", "TIMEOF");
        }
    }
}
