// Generated Time: 07/26/2020 22:52:05
// Generated By: mah

namespace System.Data.Entity.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addfieldtime : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.TB_CLASSES", "TIMEOF", c => c.String(maxLength: 50));
        }
        
        public override void Down()
        {
            DropColumn("dbo.TB_CLASSES", "TIMEOF");
        }
    }
}
