// <auto-generated />
// Generated Time: 02/28/2020 19:40:46
// Generated By: mah

namespace System.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createlogtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createlogtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202002281610469_createlogtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
