
using System;
using System.Data.Entity.Migrations.Design;
using System.Data.Entity.Migrations.Utilities;

namespace Mah.Common.EntityFramework.Migration
{
    public class MigrationUserAndTimeCodeGenerator : CSharpMigrationCodeGenerator
    {
        protected override void WriteClassStart(
            string @namespace,
            string className,
            IndentedTextWriter writer,
            string @base,
            bool designer = false,
            System.Collections.Generic.IEnumerable<string> namespaces = null)
        {
            writer.WriteLine("// Generated Time: {0}", DateTime.Now);
            writer.WriteLine("// Generated By: {0}", Environment.UserName);
            writer.WriteLine();

            base.WriteClassStart(@namespace, className, writer, @base, designer, namespaces);
        }
    }
}
